-- MySQL Script generated by MySQL Workbench
-- Sat Jul 15 13:35:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GreenGood_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GreenGood_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GreenGood_DB` DEFAULT CHARACTER SET utf8 ;
USE `GreenGood_DB` ;

-- -----------------------------------------------------
-- Table `GreenGood_DB`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GreenGood_DB`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GreenGood_DB`.`subcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GreenGood_DB`.`subcategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GreenGood_DB`.`manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GreenGood_DB`.`manufacturer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `website` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GreenGood_DB`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GreenGood_DB`.`type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GreenGood_DB`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GreenGood_DB`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `product_image` VARCHAR(45) NOT NULL,
  `info` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `discount` INT NOT NULL,
  `stock` INT NOT NULL,
  `sales_amount` DECIMAL(10,2) NULL,
  `category_id` INT NOT NULL,
  `subcategory_id` INT NOT NULL,
  `manufacturer_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_products_subcategory1_idx` (`subcategory_id` ASC) VISIBLE,
  INDEX `fk_products_manufacturer1_idx` (`manufacturer_id` ASC) VISIBLE,
  INDEX `fk_products_type1_idx` (`type_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `GreenGood_DB`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_subcategory1`
    FOREIGN KEY (`subcategory_id`)
    REFERENCES `GreenGood_DB`.`subcategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_manufacturer1`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `GreenGood_DB`.`manufacturer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `GreenGood_DB`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GreenGood_DB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GreenGood_DB`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `user_image` VARCHAR(45) NULL,
  `user_type` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `password` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GreenGood_DB`.`user_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GreenGood_DB`.`user_address` (
  `street` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`users_id`),
  CONSTRAINT `fk_user_address_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `GreenGood_DB`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GreenGood_DB`.`shopping_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GreenGood_DB`.`shopping_session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total` DECIMAL(10,2) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shopping_session_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_shopping_session_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `GreenGood_DB`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GreenGood_DB`.`cart_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GreenGood_DB`.`cart_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `products_id` INT NOT NULL,
  `shopping_session_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cart_item_products1_idx` (`products_id` ASC) VISIBLE,
  INDEX `fk_cart_item_shopping_session1_idx` (`shopping_session_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_item_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `GreenGood_DB`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_item_shopping_session1`
    FOREIGN KEY (`shopping_session_id`)
    REFERENCES `GreenGood_DB`.`shopping_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GreenGood_DB`.`user_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GreenGood_DB`.`user_payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payment_type` VARCHAR(45) NOT NULL,
  `payment_vendor` VARCHAR(45) NOT NULL,
  `account_number` VARCHAR(45) NOT NULL,
  `card_number` VARCHAR(45) NOT NULL,
  `card_exp` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_user_payment_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_payment_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `GreenGood_DB`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GreenGood_DB`.`order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GreenGood_DB`.`order_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `detail_total` DECIMAL(10,2) NOT NULL,
  `user_payment_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `order_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_details_user_payment1_idx` (`user_payment_id` ASC) VISIBLE,
  INDEX `fk_order_details_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_details_user_payment1`
    FOREIGN KEY (`user_payment_id`)
    REFERENCES `GreenGood_DB`.`user_payment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_details_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `GreenGood_DB`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GreenGood_DB`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GreenGood_DB`.`order_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `order_details_id` INT NOT NULL,
  `cart_item_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_items_order_details1_idx` (`order_details_id` ASC) VISIBLE,
  INDEX `fk_order_items_cart_item1_idx` (`cart_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_items_order_details1`
    FOREIGN KEY (`order_details_id`)
    REFERENCES `GreenGood_DB`.`order_details` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_items_cart_item1`
    FOREIGN KEY (`cart_item_id`)
    REFERENCES `GreenGood_DB`.`cart_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GreenGood_DB`.`liked_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GreenGood_DB`.`liked_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_liked_products_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_liked_products_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_liked_products_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `GreenGood_DB`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_liked_products_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `GreenGood_DB`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
